[versions]
shadow = "9.6.1"
paper-yml = "0.9.0"
minotaur = "2.9.0"

paper-api = "1.21.6-R0.1-SNAPSHOT"
voicechat-api = "2.6.20"
lavaplayer = "2.2.7"
youtube-source = "b33460b38ad13b5cd07da75e46444397cf0ea2df-SNAPSHOT"
commons-io = "2.22.0"
bstats = "3.2.1"
simple-yaml = "1.8.4"
lombok = "1.18.46"
packetevents = "2.13.0"
folialib = "0.5.2"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
paper-yml = { id = "de.eldoria.plugin-yml.paper", version.ref = "paper-yml" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
voicechat-api = { module = "de.maxhenkel.voicechat:voicechat-api", version.ref = "voicechat-api" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
folialib = { module = "com.tcoded:FoliaLib", version.ref = "folialib" }

lavaplayer = { module = "dev.arbjerg:lavaplayer", version.ref = "lavaplayer" }
lavaplayer-youtube = { module = "dev.lavalink.youtube:common", version.ref = "youtube-source" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
simple-yaml = { module = "me.carleslc:Simple-Yaml", version.ref = "simple-yaml" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
