name: CDAPITEST
version: ${version}
main: "space.subkek.cdapitest.Main"
api-version: "1.21"
folia-supported: true
dependencies:
  server:
    voicechat:
      load: BEFORE
      required: true
      join-classpath: true
    CustomDiscs:
      load: BEFORE
      required: true
      join-classpath: true
